---
- name: "Create UUID Pool"
  vars:
    api_info: &api_info
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  cisco.intersight.intersight_rest_api:
      <<: *api_info
      resource_path: /uuidpool/Pools
      query_params:
         $filter: "Name eq '{{ name_of_uuid_pool }}'"
      api_body: {
        "Name": "{{ name_of_uuid_pool }}",
        "Description": "{{ description_of_uuid_pool }}",

        "Organization": {
           "Moid": "{{ intersight_org.api_response.Moid }}"
         },
        Tags: [{Key: "configmode", Value: "ansible"},{Key: "prefix", Value: "{{ prefix }}"}],

        "AssignmentOrder": "default",
        "Prefix": "{{ uuid_prefix }}",
        "UuidSuffixBlocks": [
          {
              "From": "{{ uuid_from }}",
              "Size": "{{ uuid_size }}"
          }
        ]
       }
  register: uuid_pool
