---
# Create and Deploy the server profile template(s). Users can derive one or more server profiles
# from these templates

- name: "Create Server Profile Templates"
  hosts: localhost
  gather_facts: no

  # Create Server PoProfile Templates
  roles:
    - role: create_server_profile_template