---
# Procedures to setup iSCSI paramters on the ESXi Hosts
#
# Add the NTP Server(s) to the ESXi Hosts
- include_tasks: add_esxi_ntp.yml
# Modify the iSCSI-A vSwitch and add iSCSI-B vSwitch
- include_tasks: modify_esxi_iscsi_vswitch.yml
# Create the iSCSI-B Port-Group on iSCSI-B vSwitch
- include_tasks: create_esxi_iscsiB_PG.yml
# # Modify the iSCSI-A VMK MTU and create iSCSI-B VMK
- include_tasks: create_esxi_iscsi_vmk.yml
# Add iSCSI Targets for Multi Path
- include_tasks: add_esxi_iscsi_targets.yml
# Rescan HBA's for the ESXi host and refresh storage system objects
- include_tasks: rescan_esxi_iscsi_HBA.yml
