---
# This task configures VDS on the vCenter

- name: vCenter vDS creation
  community.vmware.vmware_dvswitch:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    validate_certs: false
    datacenter_name: '{{ vcenter_dc }}'
    switch_name: '{{ dvs_name }}'
    # version: '{{ dv_version }}' - Use latest version 7.0
    version: '{{ dv_version }}'
    # Best practices dictate mtu should always be 9000 therefore the value is hardcoded
    # mtu: '{{ dv_mtu }}'
    mtu: 9000
    uplink_quantity: '{{ dv_uplink }}'
    discovery_protocol: '{{ dv_protocol }}'
    discovery_operation: '{{ dv_operation }}'
    state: present
    # delegate_to: localhost
