---
# Variables defined here are specific to MDS-A
#
#  Variables used to create port channel to UCS.
port_channel_id: 103
port_channel_speed: "32000"
port_channel_description: "AA03-6536-A"
#
#  VSAN number to use used for a the fabric being created
vsan_id: "{{ vsan_list[0].vsan_id}}"
vsan_name: "{{ vsan_list[0].name}}"
#
# The zone name and zoneset names used in the configuration
zoneset_name: Fabric-A
fcp_zone_name: Infra-VSI-Fabric-A
fc_nvme_zone_name: Infra-NVMe-VSI-Fabric-A


#
# Device alias list using device names and PWWNs from CVD.  Update the PWWNs to match your deployment
# Any changes made to the device names will always need to be updated in the Zoning List below
fcp_device_alias_list:
  - device_name: FlashArray-XL-CT0FC0
    pwwn: "{{ fcp_ct0_fc0 }}"
    dev_type: target
  - device_name: FlashArray-XL-CT1FC0
    pwwn: "{{ fcp_ct1_fc0 }}"
    dev_type: target
  - device_name: VM-Host-Infra-FCP-01-A
    pwwn: "{{ ucs_host_01_a }}"
    dev_type: initiator
  - device_name: VM-Host-Infra-FCP-02-A
    pwwn: "{{ ucs_host_02_a }}"
    dev_type: initiator
  - device_name: VM-Host-Infra-FCP-03-A
    pwwn: "{{ ucs_host_03_a }}"
    dev_type: initiator

#
fc_nvme_device_alias_list:
  - device_name: FlashArray-XL-CT0FC1
    pwwn: "{{ fcp_ct0_fc1 }}"
    dev_type: target
  - device_name: FlashArray-XL-CT1FC1
    pwwn: "{{ fcp_ct1_fc1 }}"
    dev_type: target
  - device_name: VM-Host-Infra-FC-NVMe-01-A
    pwwn: "{{ ucs_nvme_host_01_a }}"
    dev_type: initiator
  - device_name: VM-Host-Infra-FC-NVMe-02-A
    pwwn: "{{ ucs_nvme_host_02_a }}"
    dev_type: initiator
  - device_name: VM-Host-Infra-FC-NVMe-03-A
    pwwn: "{{ ucs_nvme_host_03_a }}"
    dev_type: initiator

#
# MDS Switch FC Interface List
#
storage_interface_list:
  - interface: "fc1/1"
    description: "AA03-XL170-ct0fc0"
    speed: "32000"
  - interface: "fc1/2"
    description: "AA03-XL170-ct1fc0"
    speed: "32000"
  - interface: "fc1/3"
    description: "AA03-XL170-ct0fc1"
    speed: "32000"
  - interface: "fc1/4"
    description: "AA03-XL170-ct1fc1"
    speed: "32000"

#
ucs_interface_list:
  - interface: "fc1/5"
    description: "AA03-6536-A:fc1/1"
    speed: "32000"
  - interface: "fc1/6"
    description: "AA03-6536-A:fc1/2"
    speed: "32000"
  - interface: "fc1/7"
    description: "AA03-6536-A:fc1/3"
    speed: "32000"
  - interface: "fc1/8"
    description: "AA03-6536-A:fc1/4"
    speed: "32000"

