---
vpc_source: 10.255.255.2
vpc_destination:  10.255.255.1
vpc_role_priority: "20"



# NTP Distribution IP for N9K-B in the IB-MGMT VLAN
IB_MGMT_ntp_dist_IP: "{{ ib_mgmt_ntp_servers[1].ip_address }}{{ ntp_distribution_nm_cidr }}"
# Interface Lists; more interfaces can be added for additional BW
#
uplink_interface_list:
  - interface: "Ethernet1/9"
    description: "Uplink-SW"

peerlink_interface_list:
  - interface: "Ethernet1/101"
    description: "AA03-93180-A:Eth1/101"
  - interface: "Ethernet1/102"
    description: "AA03-93180-A:Eth1/102"
#
FI_A_interface_list:
  - interface: "Ethernet1/97"
    description: "AA03-6536-FI-A:Eth1/29"


#
FI_B_interface_list:
  - interface: "Ethernet1/98"
    description: "AA03-6536-FI-B:Eth1/30"


iscsi_vlan: "3219"
#
storage_interface_list:
  - interface: "Ethernet1/99"
    description: "AA03-XL170-ct0.eth5"
  - interface: "Ethernet1/100"
    description: "AA03-XL170-ct1.eth5"
#
all_interfaces: "{{ uplink_interface_list + peerlink_interface_list + FI_A_interface_list + FI_B_interface_list + storage_interface_list }}"

