---
- name: "Get IP Address Pool Details"
  vars:
    api_info: &api_info_ip_pool
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  intersight_rest_api:
    <<: *api_info_ip_pool
    resource_path: /ippool/Pools
    query_params:
      $filter: "Name eq '{{ name_of_ip_pool_for_management_access }}'"

  register:  management_ip_pool_details

- name: "Get MAC Address Details for FI-A"
  vars:
    api_info: &api_info_mac_a_pool
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  intersight_rest_api:
    <<: *api_info_mac_a_pool
    resource_path: /macpool/Pools
    query_params:
      $filter: "Name eq '{{ name_of_mac_pool_on_fi_a }}'"

  register:  mac_pool_fi_a_details

- name: "Get MAC Address Details for FI-B"
  vars:
    api_info: &api_info_mac_b_pool
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  intersight_rest_api:
    <<: *api_info_mac_b_pool
    resource_path: /macpool/Pools
    query_params:
      $filter: "Name eq '{{ name_of_mac_pool_on_fi_b }}'"

  register:  mac_pool_fi_b_details

- name: "Get WWNN Pool Details"
  vars:
    api_info: &api_info_wwnn_pool
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  intersight_rest_api:
    <<: *api_info_wwnn_pool
    resource_path: /fcpool/Pools
    query_params:
      $filter: "Name eq '{{ name_of_wwnn_pool }}'"

  register:  wwnn_pool_details
  when: configure_fc == 'true'

- name: "Get WWPN Pool Details of SAN-A"
  vars:
    api_info: &api_info_wwpn_a_pool
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  intersight_rest_api:
    <<: *api_info_wwpn_a_pool
    resource_path: /fcpool/Pools
    query_params:
      $filter: "Name eq '{{ name_of_wwpn_pool_san_a }}'"

  register:  wwpn_pool_san_a_details
  when: configure_fc == 'true'

- name: "Get WWPN Pool Details of SAN-B"
  vars:
    api_info: &api_info_wwpn_b_pool
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  intersight_rest_api:
    <<: *api_info_wwpn_b_pool
    resource_path: /fcpool/Pools
    query_params:
      $filter: "Name eq '{{ name_of_wwpn_pool_san_b }}'"

  register:  wwpn_pool_san_b_details
  when: configure_fc == 'true'

- name: "Get IQN Pool"
  vars:
    api_info: &api_info_iqn
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  cisco.intersight.intersight_rest_api:
      <<: *api_info_iqn
      resource_path: /iqnpool/Pools
      query_params:
         $filter: "Name eq '{{ name_of_iqn_pool }}'"

  register: iqn_pool_details
  when: configure_iscsi == 'true'

-  name: "Get IP Pool for iSCSI-A"
   vars:
     api_info: &api_info_iscsi_a
       api_private_key: "{{ api_private_key }}"
       api_key_id: "{{ api_key_id }}"
       api_uri: "{{ api_uri | default(omit) }}"
       validate_certs: "{{ validate_certs | default(omit) }}"
       state: "{{ state | default(omit) }}"

   cisco.intersight.intersight_rest_api:
        <<: *api_info_iscsi_a
        resource_path: /ippool/Pools
        query_params:
           $filter: "Name eq '{{ name_of_ip_pool_for_iscsi_a }}'"

   register: iscsi_a_ip_pool_details
   when: configure_iscsi == 'true'


-  name: "Get IP Pool for iSCSI-B"
   vars:
     api_info: &api_info_iscsi_b
       api_private_key: "{{ api_private_key }}"
       api_key_id: "{{ api_key_id }}"
       api_uri: "{{ api_uri | default(omit) }}"
       validate_certs: "{{ validate_certs | default(omit) }}"
       state: "{{ state | default(omit) }}"


   cisco.intersight.intersight_rest_api:
        <<: *api_info_iscsi_b
        resource_path: /ippool/Pools
        query_params:
           $filter: "Name eq '{{ name_of_ip_pool_for_iscsi_b }}'"

   register: iscsi_b_ip_pool_details
   when: configure_iscsi == 'true'
